_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 24
  WARMUP_FACTOR: 0.1

