MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardPooler"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PRINT_WINDOWSIZE:
    VIS_TRAIN: 100
    VIS_TEST: 100
  VG:
    SPATIAL_FEAT: True
    PHRASE_SELECT_TYPE: "Sum"
    MAX_PHRASE_LEN: 5
    VOCAB_FILE: "./RefSegDatasets/refseg_anno_new/refcoco+/vocab.json"
    FEAT_SOURCE: 'bbox'
    USE_EDGE_STRUCT: True
    USE_REL_FEAT: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2

  BACKBONE:
      NAME: "build_deeplabv2_backbone"
      PRETRAIN_PATH: './RefSegDatasets/refseg_anno_new/backbone_weight/deeplabv2.pth'



DATASETS:
  TRAIN: ("refcoco+_train",)
  TEST: ("refcoco+_val",)

SOLVER:
  MASK_SOFTMAX: True
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"  ## "WarmupPolyLR"
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (20000, 40000)
  MAX_ITER: 1000
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_NORM: 0.0005
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  POLY_POWER: 0.9
  POLY_END_LR: 0.00001
  CHECKPOINT_PERIOD: 4000
  BACKBONE_LR_FACTOR: 0.1
  FIX_BACKBONE: False
  FIX_BACKBONE_BN: False
  USING_APEX: False
  OPTIMIZER: "Adam"  # Sgd
  INIT_PARA: True

INPUT:
  MIN_SIZE_TRAIN: (321,)
  MIN_SIZE_TEST: 321

TEST:
  EVAL_PERIOD: 4000





